language: node_js
node_js:
  - '6.10'
branches:
  only:
    - develop
    - master
    - "/^feature\\/.*$/"
    - "/^release\\/.*$/"
cache: yarn
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
